# author: Fabian Dirscherl
# ... And thanks to jesus riding unicorns puking rainbows and 
# farting glitter - aka @TimeForANinja - it finally works
version: "3.0"
services:
  backend:
    build: ./spring-petclinic-rest/
    ports:
      - "9966:9966"

  frontend:
    build: ./spring-petclinic-angular/
    ports:
      - "4200:8080"

  traefik:
    build: ./proxy/
    ports:
      - "80:80"
